### ISSUE TITLE
keine Verbindung zu BioStar17 möglich via HomeAssistant

### ISSUE THREAD

**Issue by FlorianH81** [a529987659852/GuntamaticBiostar#1]
Hallo, erst einmal danke für die Integration in HomeAssistant
Ich habe den API Code von Guntamatic erhalten und wollte nun die Heizung in HA einbinden, leider kann ich keine Verbindung herstellen

Hier mal ein Trace aus HA
2024-02-05 17:17:27.757 ERROR (MainThread) [custom_components.GuntamaticBiostar] Unexpected error fetching GuntamaticBiostar data: unexpected character: line 1 column 10 (char 9)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/GuntamaticBiostar/__init__.py", line 178, in _async_update_data
    currentData = await self.my_api._async_get_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/GuntamaticBiostar/__init__.py", line 78, in _async_get_data
    dataDescription = await resp.json()
                      ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 71, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1182, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 43, in json_loads
    return orjson.loads(__obj)  # type:ignore[no-any-return]

Wenn ich einen curl -v auf die Heizung über die CLI des Servers mache auf die Heizung bekomme ich die Werte entsprechend zurück.
Kannst du mir hier helfen?

Besonderheit: Die Heizung steht in einem anderen VLAN, der HA Server darf hier aber hin
HA läuft als Docker Container

**Comment by oscarminus** [comment]
Hi, das klingt nach dem Bug den ich auch hatte. Ich habe bereits einen Pullrequest (#2) eingestellt der das Problem für mich behoben hat.

**Comment by FlorianH81** [comment]
Hallo, hab den angepassten Code von dir eingebaut und HA neu gestartet, Verbindung kann jetzt hergestellt werden und ich kann die Werte auslesen, vielen Dank

**Comment by FlorianH81** [comment]
Hallo, hab den angepassten Code von dir eingebaut und HA neu gestartet, Verbindung kann jetzt hergestellt werden und ich kann die Werte auslesen, vielen Dank

**Comment by a529987659852** [comment]
Solved with release 0.2.8
