### ISSUE TITLE
Fehler "Unexpected error fetching GuntamaticBiostar data"

### ISSUE THREAD

**Issue by innogkph** [a529987659852/GuntamaticBiostar#8]
Hallo zusammen, leider bekomme ich in HA immer folgenden Fehler. Den Key (Level 1) habe ich von Guntamatic bekommen und bei der Einrichtung entsprechend eingetragen. Woran könnte das liegen?

Logger: custom_components.GuntamaticBiostar
Quelle: helpers/update_coordinator.py:379
Integration: GuntamaticBiostar (Dokumentation, Probleme)
Erstmals aufgetreten: 13:37:04 (5 Vorkommnisse)
Zuletzt protokolliert: 13:37:35

Unexpected error fetching GuntamaticBiostar data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/GuntamaticBiostar/__init__.py", line 178, in _async_update_data
    currentData = await self.my_api._async_get_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/GuntamaticBiostar/__init__.py", line 83, in _async_get_data
    key = dataDescription[i].get("name")
          ~~~~~~~~~~~~~~~^^^
KeyError: 0

**Comment by dj5td** [comment]
Found the root cause: on firmware 3.x, `/ext/daqdesc.cgi`/`/ext/daqdata.cgi` return `{"err":"Keine Berechtigung"}` instead of a list, regardless of the API key — that's what triggers the `KeyError: 0`. Opened #10 with a fix that falls back to the legacy `/daqdesc.cgi`/`/daqdata.cgi` endpoints (which work fine even without a key) instead of crashing.
